# -*- coding: utf-8 -*-
"""selection_test_rank.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z44nKPxcyoDOy0b2BCNaQD4Z-ZOl0iYs
"""

from random import uniform, choice, choices
from operator import attrgetter


def fps(population):
    """Fitness proportionate selection implementation.

    Args:
        population (Population): The population we want to select from.

    Returns:
        Individual: selected individual.
    """

    if population.optim == "max":
        # Sum total fitness
        total_fitness = sum([i.fitness for i in population])
        # Get a 'position' on the wheel
        spin = uniform(0, total_fitness)
        position = 0
        # Find individual in the position of the spin
        for individual in population:
            position += individual.fitness
            if position > spin:
                return individual

    elif population.optim == "min":
        # Sum total fitness
        total_fitness = sum([i.fitness for i in population])
        # Get a 'position' on the wheel
        spin = uniform(0, total_fitness)
        spin = 1 - spin
        position = 0
        # Find individual in the position of the spin
        for individual in population:
            position += individual.fitness
            if position > spin:
                return individual

    else:
        raise Exception("No optimization specified (min or max).")


def tournament(population, size=10):
    """Tournament selection implementation.

    Args:
        population (Population): The population we want to select from.
        size (int): Size of the tournament.

    Returns:
        Individual: Best individual in the tournament.
    """

    # Select individuals based on tournament size
    tournament = [choice(population.individuals) for i in range(size)]
    # Check if the problem is max or min
    if population.optim == 'max':
        return max(tournament, key=attrgetter("fitness"))
    elif population.optim == 'min':
        return min(tournament, key=attrgetter("fitness"))
    else:
        raise Exception("No optimization specified (min or max).")

        

def rank(population):
    """Rank selection implementation.

    Args:
        population (Population): The population we want to select from.

    Returns:
        Individual: Best individual in the rank.
    """
    # Get the number of individuals in the population.
    n = len(population)
    
    # Use the gauss formula to get the sum of all ranks 
    rank_sum = n * (n + 1) / 2
    
    # Calculate the probability
    prob_list = [i/rank_sum for i in range(0, n)]

    # Select individuals based on rank size
    rank = choices(population, weights=prob_list)
    
    # Check if the problem is max or min
    if population.optim == 'max':
        return max(rank, key=attrgetter("fitness"))
    elif population.optim == 'min':
        return min(rank, key=attrgetter("fitness"))
    else:
        raise Exception("No optimization specified (min or max).")